### ISSUE TITLE
[2pt] [Group task] Kanban board created

### ISSUE THREAD

**Issue by TamaraDimov** [TamaraDimov/Catalog-of-my-things#32]
Hello,
The number of contributors on this project will be 3 (Team member 1 - @TamaraDimov , 
Team member 2 - @Nasirkhan294 , 
Team member 3 - @kifle23 ). 
We create the Kanban board with the activities for all contributes and bellow you can find the link from the repo.

https://github.com/TamaraDimov/Catalog-of-my-things

**Comment by Olamarx** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>
## Highlights
- All methods in place ✔️
- Good use of Kanban board ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
